nacimiento = input("cual es tu fecha de nacimiento: ")
#print("Dia: ", nacimiento[0:2])
#print("Mes: ", nacimiento[3:5])
#print("Ano: ", nacimiento[6:10]) 
fecha = nacimiento.split("/")
print("has nacido el dia "+fecha[0]+" del mes "+fecha[1]+" del año " +fecha[2])
